name: .NET Desktop

on:
  push:
    branches:
      - main  # Runs on push to the main branch
  pull_request:
    branches:
      - main  # Runs on pull requests to the main branch

jobs:
  build:
    runs-on: windows-latest  # Use a Windows environment to build the project

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Checkout the code from the repository

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'  # Specify .NET 8

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --configuration Release --no-restore

      - name: Run tests (optional)
        run: dotnet test --no-restore --verbosity normal

      - name: Publish app
        run: dotnet publish -c Release -r win-x64 --self-contained --no-restore

      - name: Upload artifact (optional)
        uses: actions/upload-artifact@v3
        with:
          name: published-app
          path: |
            **/bin/Release/net8.0/win-x64/publish/**  # Adjust this path if necessary
